### PR TITLE
Setup windows CI.

### LINKED ISSUE #5: Set up Windows CI

### PR DESCRIPTION
**Pull request by tomprince**
Fixes #5.

### CODE REVIEW

**Comment by tomprince** [comment]
There are a bunch of test failures, but fortunately, :upside_down_face: they don't cause the action to fail. I'd like to land this as-is, and then we can working on fixing the test suite.

**Comment by meejah** [comment]
I don't know what's going on with this, but it's showing 129 commits and a whole bunch of definitely-not-windows-CI changes for me...

**Comment by tomprince** [comment]
> I don't know what's going on with this, but it's showing 129 commits and a whole bunch of definitely-not-windows-CI changes for me...

Oh. It looks like I accidentally targeted this at the upstream branch for #18, and not `main`. I've adjusted it to be against the right branch. (I blame the github ssh message URL for generating the wrong base :slightly_smiling_face:)

**Comment by tomprince** [comment]
I also have a branch with all but ~3 tests passing (see #373), though it has a few hacks in it currently (mostly where it interacts with #369).

**Review by meejah — APPROVED** [review]
I can't provide much feedback on the "actual" changes (haven't looked at windows in a while) but the structure looks fine

**Pull request merged**
