### PR TITLE
monitor status

### LINKED ISSUE #351: magic-folder-api monitor
As part of #335 it would be great for debugging and example-code to have a command-line convenience to access the realtime status API.

### PR DESCRIPTION
**Pull request by meejah**
Fixes #351

Serves both as a debugging aid and place to have example WebSocket client code.

This PR is stacked on #335 so review/merge that one first.

### CODE REVIEW

**Comment by meejah** [comment]
Bit of a testing SNAFU here: although Autobahn does have a facility for testing a client/server interaction (see https://github.com/crossbario/autobahn-python/blob/master/autobahn/twisted/testing/__init__.py#L280) there was a bug in it that clobbered the factory (which we do need to provide here). See https://github.com/crossbario/autobahn-python/pull/1480

Although that bug is fixed, there is no release with containing the fix. _However_ even if there were a release Autobahn is now python3-only -- so a new release wouldn't help us because we have to use an older python2-supporting release anyway.

**Comment by meejah** [comment]
(p.s. @tomprince thought of a workaround for the Autobahn thing, which was pushed into the "upstream" status-api PR)

**Review by tomprince — APPROVED** [review]
Looks good. I assume you've tested this manually?

**Comment by meejah** [comment]
> Looks good. I assume you've tested this manually?

Yeah .. inclined to add at least a basic test first since you suggested the workaround for Autobahn bug.

**Pull request merged**
