### PR TITLE
fix windows unit-test that's failing

### PR DESCRIPTION
**Pull request by meejah**
Attempts to fix the failing windows unit-test.

- `long` not `int` (fixed)
- sorting seems off ...

### CODE REVIEW

**Comment by meejah** [comment]
It _looks_ like the database sorting is just broken on Windows?

I wanted to know what `sqlite3` version that build used, but I can't seem to find out where `sqlite3` comes from on Windows. The `pip freeze` output in Tox doesn't show any package named that (nor anywhere else in the raw logs from the Windows builder).

**Comment by meejah** [comment]
(it was pointed out that sqlite3 is in the stdlib)

**Comment by meejah** [comment]
After skipping that test in this branch, there's also an Eliot test failing ...

(Surely if "ORDER BY ... DESC" is broken on windows, _someone_ else would have reported? I've not had success finding that person w/ duckduckgo though...)

**Comment by tomprince** [comment]
Looking at some results, it appears that the time resolution on windows is low enough that all the entries get the same time, so the sort order is random. #541 should demonstrate that is the case, by forcing the time we use to be always increasing.

**Comment by meejah** [comment]
`test_limit` is using explicit timestamps already though?

**Comment by tomprince** [comment]
> `test_limit` is using explicit timestamps already though?

Not for `last_updated_ns`, which is what we are sorting by. That can't be controlled by the caller.

I'm going to close this in favor of #541.

**Comment by meejah** [comment]
What about the "dump actual sql version"  stuff?

**Comment by tomprince** [comment]
> What about the "dump actual sql version" stuff?

Sure, we could keep that, though given that it *wasn't* an sqlite3 bug, I suspect that is less valuable. I'd be inclined to cherry-pick that code to its own PR though. (Or at least rebase this one to just have those changes).

**Pull request merged**
