### PR TITLE
remove _get_json_for_fragment() from cli

### PR DESCRIPTION
**Pull request by vu3rdd**
Integration test use `_get_json_for_fragment()`, so this has been modified to use the new status API.

### CODE REVIEW

**Comment by meejah** [comment]
Hmm, does this mean the new status API doesn't need a token??

**Comment by vu3rdd** [comment]
> Hmm, does this mean the new status API doesn't need a token??

It is being accessed inside the `status()` function, it looks like: https://github.com/LeastAuthority/magic-folder/blob/master/src/magic_folder/status.py#L71

**Comment by meejah** [comment]
Ahhh I see. Sorry, read it too fast :)

**Comment by vu3rdd** [comment]
Thanks. I will keep it open for now until #87 is in and after that will do a CI run and then merge once it is all green.

**Pull request merged**
